before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- main: main.go
  binary: sshh
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - 386
archive:
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  format: zip
  format_overrides:
  - goos: windows
    format: zip
brew:
  github:
    owner: sakoken
    name: homebrew-sshh
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  description: "ssh hosts manager"
  homepage: "https://github.com/sakoken/sshh"
  install: |
    bin.install "sshh"